name: Version Metadata
author: Jannik Wibker
description: An action that allows you to check whether your npm package version has been updated

inputs:
  file:
    description: The path to the package.json file
    required: false
    default: package.json
  token:
    description: GitHub token used for authentication (you can use secrets.GITHUB_TOKEN)
    required: false
  version-extraction-override:
    description: |
      Optionally override how the version is extracted from the file. This is useful in the rare cases you don't use a package.json file but some other format.
      This option supports two modes of operation:
      - regex: A regular expression that matches the version number in the file. This is supplied in the following way: `regex:<the regex matching the version number>`
      - command: A command that is passed the file contents via stdin and outputs the version number. This is supplied in the following way: `command:<the command that extracts the version number>`

      Examples:
      - regex: `regex:(\\d+\\.\\d+\\.\\d+)`
      - command: `command:jq -r .version`

      It is to be noted that this isn't a fully supported feature and any issues that arise may not be fixed in a timely manner.
    required: false

outputs:
  changed:
    description: Has the version changed since the last time the action was run?
  type:
    description: The type of version change ('major', 'minor', 'patch', 'pre-release')
  oldVersion:
    description: Previous version number, current version if nothing changed
  newVersion:
    description: New version number, current version if nothing changed
  commitResponsible:
    description: The SHA of the commit that last changed the version number
  commitBase:
    description: commit SHA of the base commit (previous head before pushing / merging new commits)
  commitHead:
    description: commit SHA of the head commit
  changedFiles:
    description: All files changed between the examined commits, categorized by type (added, modified, removed, renamed, all)
  changes:
    description: List of all changes to the version number since the last time the action was run. This includes old version, new version, type of change, and the commit SHA for each change.
  json:
    description: all of the above as stringified JSON (as you'd otherwise have to combine things back together again)

runs:
  using: node16
  main: 'dist/index.js'

branding:
  icon: package
  color: purple
