name: PR Gate
on: push

jobs:
  pr-gate:
    name: PR Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2
        with:
          version: 9.14.4
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm --filter "*" lint
      - run: pnpm --filter "*" build

      - name: run version-metadata tests
        run: ./index.mjs
        working-directory: version-metadata/test
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
