name: PR Gate
on: push

jobs:
  pr-gate:
    name: PR Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@latest
        with:
          version: 6.32.2
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm --filter "*" lint
      - run: pnpm --filter "*" build
