name: PR Gate
on: push

jobs:
  pr-gate:
    name: PR Gate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 6.32.2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: pnpm

      - run: pnpm install
      - run: pnpm --filter "*" lint
      - run: pnpm --filter "*" build

      - name: run version-metadata tests
        run: ./index.mjs
        working-directory: version-metadata/test
        env:
          INPUT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
